---
grails:
    profile: web
    codegen:
        defaultPackage: au.org.ala.bie
    gorm:
        reactor:
            # Whether to translate GORM events into Reactor events
            # Disabled by default for performance reasons
            events: false
info:
    app:
        name: '@info.app.name@'
        version: '@info.app.version@'
        grailsVersion: '@info.app.grailsVersion@'
spring:
    jmx:
        unique-names: true
    main:
        banner-mode: "off"
    groovy:
        template:
            check-template-location: false
    devtools:
        restart:
            additional-exclude:
                - '*.gsp'
                - '**/*.gsp'
                - '*.gson'
                - '**/*.gson'
                - 'logback.groovy'
                - '*.properties'
management:
    endpoints:
        enabled-by-default: false

---
grails:
    config:
        locations:
            - file:///data/ala-bie-hub/config/ala-bie-hub-config.properties
            - file:///data/ala-bie-hub/config/ala-bie-hub-config.yml
            - file:///data/ala-bie-hub/config/ala-bie-hub-config.groovy
    mime:
        disable:
            accept:
                header:
                    userAgents:
                        - Gecko
                        - WebKit
                        - Presto
                        - Trident
        types:
            all: '*/*'
            atom: application/atom+xml
            css: text/css
            csv: text/csv
            form: application/x-www-form-urlencoded
            html:
                - text/html
                - application/xhtml+xml
            js: text/javascript
            json:
                - application/json
                - text/json
            multipartForm: multipart/form-data
            pdf: application/pdf
            rss: application/rss+xml
            text: text/plain
            hal:
                - application/hal+json
                - application/hal+xml
            xml:
                - text/xml
                - application/xml
    urlmapping:
        cache:
            maxsize: 1000
    controllers:
        defaultScope: singleton
    converters:
        encoding: UTF-8
    views:
        default:
            codec: html
        gsp:
            encoding: UTF-8
            htmlcodec: xml
            codecs:
                expression: html
                scriptlet: html
                taglib: none
                staticparts: none
    serverURL: http://localhost:8080
management:
    endpoints:
        jmx:
            unique-names: true

---
#Required so that the gbif-ecat library does not bugger up initialisation from its internal application.properties
app:
    name: ala-bie-hub
    dataDir: /tmp/gbif-ecat
security:
    cas:
        #    applyUriFiltersToTicketValidation: false
        casServerName: https://auth.ala.org.au
        appServerName: http://localhost:8080

skin:
    homeUrl: http://www.ala.org.au
    layout: ala-main
    orgNameLong: Atlas of Living Australia
    fluidLayout: true
    orgNameShort: Atlas of Living Australia
    favicon: https://www.ala.org.au/app/uploads/2019/01/cropped-favicon-32x32.png
facebook:
    app_id: "<id>"
bie:
    baseURL: http://devt.ala.org.au:8080
    searchPath: /search
    index:
        url: https://bie-ws.ala.org.au/ws

facets: idxtype,rank,speciesGroup,locatedInHubCountry,imageAvailable,conservationStatusAUS_s,conservationStatusACT_s,conservationStatusNSW_s,conservationStatusQLD_s,conservationStatusVIC_s,conservationStatusTAS_s,conservationStatusSA_s,conservationStatusWA_s,conservationStatusNT_s
speciesParent: https://lists.ala.org.au/iconic-species
serverName: http://localhost:8080
projectNameShort: Atlas
projectName: Atlas of Living Australia
biocache:
    baseURL: https://biocache.ala.org.au
biocacheService:
    baseURL: https://biocache-ws.ala.org.au/ws
    queryContext:
dataquality:
    enabled: false
    baseUrl: https://data-quality-service.ala.org.au/data-profiles
qualityProfile: ALA
spatial:
    baseURL: https://spatial.ala.org.au
layersService:
    baseURL: https://spatial.ala.org.au/ws
ala:
    baseURL: https://www.ala.org.au
collectory:
    baseURL: https://collections.ala.org.au
    threatenedSpeciesCodesUrl: https://collections.ala.org.au/public/showDataResource
regions:
    baseURL: https://regions.ala.org.au
bhl:
    baseURL: https://www.biodiversitylibrary.org
speciesList:
    baseURL: https://lists.ala.org.au
    preferredSpeciesListDruid:
    preferredListName: ALA Preferred Species Images
    apiKey:
alerts:
    baseUrl: https://alerts.ala.org.au/ws/
sightings:
    url: https://www.ala.org.au/home/record-a-sighting/
eol:
    lang: en
defaultDecimalLatitude: -25.61
defaultDecimalLongitude: 134.35
defaultZoomLevel: 4
image:
    thumbnailUrl: https://images.ala.org.au/image/proxyImageThumbnail?imageId=
map:
    default:
        id:
        token:
        url: https://cartodb-basemaps-{s}.global.ssl.fastly.net/light_all/{z}/{x}/{y}.png
        attr: Map data &copy; <a href='https://www.openstreetmap.org/copyright'>OpenStreetMap</a>, imagery &copy; <a href='https://cartodb.com/attributions'>CartoDB</a>
        domain: abcd
        colour: e6704c
    simpleMapButton: false
    records:
        colour: e6704c
bieService:
    baseUrl: https://bie-ws.ala.org.au/ws
    queryContext:
    apiKey:
googleMapsApiKey: "<key value>"
languageCodesUrl: /languages.json
geocode.querySuffix:
occurrenceCounts:
    enabled: true
additionalResultsFields: kingdom
admin_role: ROLE_ADMIN
allowedImageEditingRoles: ROLE_ADMIN
additionalMapFilter:
synonymsTypes: synonym
literature:
    bhl:
        url: https://www.biodiversitylibrary.org
        api: https://www.biodiversitylibrary.org/api3
        apikey: "<key value>"
        fulltext: false
        pageSize: 200
        extend: false
    genbank:
        url: https://www.ncbi.nlm.nih.gov
    scholar:
        url: https://scholar.google.com.au
    google:
        url: https://www.google.com.au
    trove:
        url: https://trove.nla.gov.au
        api: https://api.trove.nla.gov.au
        apikey: "<key value>"
show:
    tabs: overview,gallery,names,classification,records,literature,sequences,data-partners

vernacularName:
    # A category of vernacular names pulled out from the standard list and given special display treatment
    pull:
        categories:
        active: false
        label: Special Common Names
        labelDetail: Common names with a special status
        showHeader: false
        showLanguage: false
external:
    eol:
        search:
            # {0}= name to search for, {1} = filter string
            # service: https://eol.org/api/search/1.0.json?q={0}&page=1&exact=true&filter_by_string={1}&cache_ttl=
            service: https://eol.org/api/search/1.0.json?q={0}&page=1&exact=true&cache_ttl=
        page:
            # {0} = page id
            service: https://eol.org/api/pages/1.0/{0,number,#0}.json?language={1}&images_per_page=0&videos_per_page=0&sounds_per_page=0&maps_per_page=0&texts_per_page=30&subjects=overview&licenses=all&details=true&references=true&vetted=0&cache_ttl=
    blacklist: file:./src/test/resources/test-blacklist.json
---
#headerAndFooter:
#    baseURL: "https://www.ala.org.au/commonui-bs3-2019"
#    version: 2
# Header and footer
headerAndFooter:
    baseURL: https://www-test.ala.org.au/commonui-bs3-2019
    version: 2

security:
    cas:
        enabled: false
    oidc:
        enabled: true
        discoveryUri: https://auth-test.ala.org.au/cas/oidc/.well-known
        scope: openid,profile,email,ala,roles, user_defined
    #        allowUnsignedIdTokens: true
    jwt:
        enabled: true
        discoveryUri: https://auth-test.ala.org.au/cas/oidc/.well-known
        fallbackToLegacyBehaviour: true


